PAGE_MARGIN = 56

KICKER_SIZE = 8.2
KICKER_TRACKING = 2.6

BRAND_SIZE = 12.5
BRAND_TRACKING = 4.2

TITLE_SIZE = 34
TITLE_LEADING = 40

SUBTITLE_SIZE = 10.8
SUBTITLE_LEADING = 16.5

LABEL_SIZE = 7.6
LABEL_TRACKING = 2.0
VALUE_SIZE = 11.5

FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"

CARD_TITLE_SIZE = 13.5
CARD_LABEL_SIZE = 8.5
CARD_LABEL_TRACKING = 1.8
CARD_BODY_SIZE = 9.6
CARD_BODY_LEADING = 13.6

SECTION_TITLE_SIZE = 22
SECTION_TITLE_LEADING = 27
SECTION_BODY_SIZE = 10.6
SECTION_BODY_LEADING = 16