PAGE_MARGIN = 56

KICKER_SIZE = 8.2
KICKER_TRACKING = 2.6

BRAND_SIZE = 12.5
BRAND_TRACKING = 4.2

TITLE_SIZE = 34
TITLE_LEADING = 40

SUBTITLE_SIZE = 10.8
SUBTITLE_LEADING = 16.5

LABEL_SIZE = 7.6
LABEL_TRACKING = 2.0
VALUE_SIZE = 11.5

FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"

CARD_TITLE_SIZE = 13.5
CARD_LABEL_SIZE = 8.5
CARD_LABEL_TRACKING = 1.8
CARD_BODY_SIZE = 9.6
CARD_BODY_LEADING = 13.6

SECTION_TITLE_SIZE = 22
SECTION_TITLE_LEADING = 27
SECTION_BODY_SIZE = 10.6
SECTION_BODY_LEADING = 16

SCORE_SIZE = 52
SCORE_UNIT_SIZE = 12.5

CATEGORY_NAME_SIZE = 10.2
CATEGORY_VALUE_SIZE = 9.6
CATEGORY_ROW_H = 30
CATEGORY_BAR_H = 7

COLUMN_KICKER_SIZE = 8.6
COLUMN_KICKER_TRACKING = 1.8
ITEM_SIZE = 9.8
ITEM_LEADING = 13.6
ITEM_GAP = 9

FINDING_CATEGORY_SIZE = 8.2
FINDING_CATEGORY_TRACKING = 2.0
FINDING_TITLE_SIZE = 18
FINDING_TITLE_LEADING = 23
FINDING_BODY_SIZE = 10.4
FINDING_BODY_LEADING = 15.4
FINDING_IMPACT_SIZE = 10.0
FINDING_IMPACT_LEADING = 14.8

CTA_TEXT_SIZE = 15.5
CTA_NOTE_SIZE = 9.4

CONTACT_LABEL_SIZE = 7.6
CONTACT_LABEL_TRACKING = 1.8
CONTACT_VALUE_SIZE = 10

TAGLINE_SIZE = 10

BENEFIT_TITLE_SIZE = 11.5
BENEFIT_DESC_SIZE = 9.6
BENEFIT_DESC_LEADING = 13.4

FLOW_LABEL_SIZE = 8.4

CHART_LABEL_SIZE = 8.2
CHART_PAD_TOP = 26
CHART_PAD_BOTTOM = 22

STAT_LABEL_SIZE = 8.2
STAT_LABEL_TRACKING = 1.8
STAT_VALUE_SIZE = 15.5

INTERPRETATION_SIZE = 11
INTERPRETATION_LEADING = 16.5

RAIL_X_OFFSET = 12
CONTENT_X_OFFSET = 50

TIER_LABEL_SIZE = 9.5
TIER_LABEL_TRACKING = 2.0
TIER_DESC_SIZE = 9.6
TIER_DESC_LEADING = 13.6

ITEM_TITLE_SIZE = 11
ITEM_TITLE_LEADING = 15
ITEM_DESC_SIZE = 9.4
ITEM_DESC_LEADING = 13.2
ITEM_TAG_SIZE = 8

TIER_GAP = 30
ITEM_GAP = 0

TIERS = [
    ("now", "01", "RESOLVER AGORA",
     "Ações de impacto rápido que não deveriam esperar."),
    ("next", "02", "PRÓXIMA ETAPA",
     "Melhorias que valem entrar no planejamento."),
    ("future", "03", "SEGUNDA ETAPA",
     "Oportunidades para depois que o essencial estiver resolvido."),
]